version: '3.8'

services:
  # Сервис для вашего приложения
  app:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    command: ['python', 'main.py']
    depends_on:
      - redis
      - celery_worker
      - celery_beat

  # Сервис для Celery Worker
  celery_worker:
    build: .
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always

  # Сервис для Celery Beat
  celery_beat:
    build: .
    command: ["celery", "-A", "tasks", "beat", "--loglevel=info"]
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always

  # Сервис для Redis
  redis:
    image: "redis:latest"
    restart: always
