version: '3.8'

services:
  # Сервис для вашего приложения
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    command: ["poetry", "run", "python", "main.py"]
    depends_on:
      - redis
      - celery_worker
      - celery_beat

  # Сервис для Celery Worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["poetry", "run", "celery", "-A", "tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis

  # Сервис для Celery Beat
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["poetry", "run", "celery", "-A", "tasks", "beat", "--loglevel=info"]
    depends_on:
      - redis

  # Сервис для Redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
